<?xml version='1.0' encoding='utf-8'?>
<package format="3">
  <name>descriptions</name>
  <version>0.6.1</version>
  <description>The descriptions package</description>

  <maintainer email="ha.rg@yandex.ru">Nikitok</maintainer>
       
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>ros_gz_sim</exec_depend>
  <exec_depend>ros_gz_bridge</exec_depend>
  <exec_depend>xacro</exec_depend>
  <exec_depend>rclpy</exec_depend>
  <exec_depend>std_msgs</exec_depend>

  <test_depend>ament_cmake_pytest</test_depend>
  <test_depend>xacro</test_depend> 

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
