<?xml version='1.0' encoding='utf-8'?>
<package format="3">
  <name>gazebo_worlds</name>
  <version>0.0.1</version>
  <description>Loaging world package</description>

  <license>MIT</license>

  <maintainer email="ha.rg@yandex.ru">Nikitok</maintainer>
  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>ros_gz_sim</depend>

  <export>
    <gazebo_ros gazebo_model_path="${prefix}/models" />
    <build_type>ament_cmake</build_type>
  </export>
</package>
